theme: jekyll-theme-cayman
title: "Bolão Quina Imbatível"
description: "30 jogos otimizados por IA – R$19,90/mês – 7 dias de garantia"
show_downloads: false
google_analytics: # deixe vazio por enquanto
